import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import LayoutWrapper from "@/components/LayoutWrapper";
import Providers from "./providers";
import VisitTracker from "@/components/VisitTracker";
import { sfPro } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Dalis Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sfPro.variable}>
      <body
        className="font-sans antialiased flex flex-col min-h-screen overflow-x-hidden bg-transparent"
      >
        <Providers>
          <Navbar />
          <LayoutWrapper>{children}</LayoutWrapper>
          <VisitTracker />
        </Providers>
      </body>
    </html>
  );
}