import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import LayoutWrapper from "@/components/LayoutWrapper";
import Providers from "./providers";
import VisitTracker from "@/components/VisitTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dalis Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/*
        KEY FIXES:
        - `flex flex-col` on body so LayoutWrapper's flex-1 / shrink-0 children work
        - `min-h-screen` ensures the body fills the viewport
        - `overflow-x-hidden` prevents horizontal scroll from any section overflows
        - `dark` class kept so body.dark CSS tokens apply
      */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen overflow-x-hidden bg-transparent dark`}
      >
        <Providers>
          <Navbar />
          <LayoutWrapper>{children}</LayoutWrapper>
          <VisitTracker />
        </Providers>
      </body>
    </html>
  );
}